TIME=/usr/bin/time -f "\n  real      %E\n  real [s]  %e\n  user [s]  %U\n  sys  [s]  %S\n  mem  [KB] %M\n  avgm [KB] %K"

# simulation of use cases
uc1:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl

uc2:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl

uc3a:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
uc3b:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl

uc7a:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
uc7b:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
uc7c:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl


	
# simulation of exception cases
ec1:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl

ec7a:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
ec7b:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
ec7c:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
ec7d:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
ec7e:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
ec7f:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl

ec8a:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
ec8b:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
ec8c:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl

ec9a:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
ec9b:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
ec9c:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
	
ec10a:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
ec10b:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
ec10c:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl

ec11a:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
ec11b:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
ec11c:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
	
ec12a:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
ec12b:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
ec12c:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl

ec20a:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
ec20b:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
ec20c:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl
	
ec21:
	${TIME} scasp -s0 --dcc ../model-original-wcache.pl ./$@.pl